language: python
os: linux
dist: bionic
python: 3.7

branches:
  only:
  - master

cache: 
  pip: true
      
install: pip install -r requirements.txt
script: 
  - python update.py
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - sh ci-push.sh

notifications:
  slack:
    secure: "isjPqS1DcuKszMnA8aFELAHpfikMy3Lt2MW+pKqHZEbKXpeVXjEc6gbJwqucNxqux0deKRbyDt0/6ARO/H9QCjhr2Wi9tXQgShqPn61pCtMMF/vEXO214fwg7c20Q+rqLInMWiB8VaLsJe95gLtFgbaNqQHzCCeF+E7yAVkdhs75OD7Po68E4ZtNOh7iw84yW1F7HRSQOX2lS7urpb4QCWQMUkjbpJprpIgZHtjFH1gLq2+Ge0EmctgqfL4DN4WdNwneWpOo3guteQ0uYSIW/eBZ+Q5K52obRKWNWbl/CWWIKzz5m429A9zJiqaf0SQid3mpU01EOCDvmaPOclLoVisJ94BlQ1sxbx3Q2CqFhyuFEESXViGRbS8CZuSro24LsMJ7TRLSxwmcONoiON7UdZyS+C0xbRYCDCtzW4a3blG/LcDOF7ikvKsRzTmdKc/J3BPUon/AmXK9lub6ige0QtdJu7PbD3RkRxxQ07MLo9NmwrTtWRhKAAxzLQDOzLWlSjkd0Mn6UpcGeoJbZFsPyO3NVu7R0Nh/ArbQKyQmPy8cI76FTKy6CyCnvGsf2KKkzUViWT4mTD+/icB3EL5uIW/qi4XHu5njyLnn+xsVvi2Kc6Ny1lnIrPolfGGL0jZuAbbpG/brJmbmibqIoM59oao06yUvwhQLjLWKFbiecBw="
